-- Ported from the origin/main (Cordtus) lineage: the objects local main lacks
-- (IBC suite, chain params, chain features). Generated by port_ibc.py.

BEGIN;

DROP TYPE IF EXISTS api.message_with_error CASCADE;

DROP TRIGGER IF EXISTS trg_ibc_denom_pending_notify ON api.ibc_denom_pending;

DROP TRIGGER IF EXISTS trg_queue_ibc_denoms ON api.messages_main;

-- Create a composite type for the return value that includes transaction error
CREATE TYPE api.message_with_error AS (
  id TEXT,
  message_index INT,
  type TEXT,
  sender TEXT,
  mentions TEXT[],
  metadata JSONB,
  error TEXT
);

-- Chain parameters (populated by chain-params-daemon)
CREATE TABLE IF NOT EXISTS api.chain_params (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- IBC connections (comprehensive info from gRPC queries)
CREATE TABLE IF NOT EXISTS api.ibc_connections (
  channel_id TEXT NOT NULL,
  port_id TEXT NOT NULL,
  connection_id TEXT,
  client_id TEXT,
  counterparty_chain_id TEXT,
  counterparty_channel_id TEXT,
  counterparty_port_id TEXT,
  counterparty_client_id TEXT,
  counterparty_connection_id TEXT,
  state TEXT,
  ordering TEXT,
  version TEXT,
  client_status TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  PRIMARY KEY (channel_id, port_id)
);

-- IBC denom traces (resolved from ibc/HASH to base denom)
CREATE TABLE IF NOT EXISTS api.ibc_denom_traces (
  ibc_denom TEXT PRIMARY KEY,
  base_denom TEXT NOT NULL,
  path TEXT NOT NULL,
  source_channel TEXT,
  source_chain_id TEXT,
  symbol TEXT,
  decimals INT DEFAULT 6,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =============================================================================
-- IBC DENOM PENDING TABLE
-- Queue for IBC denoms that need resolution via gRPC
-- =============================================================================

CREATE TABLE IF NOT EXISTS api.ibc_denom_pending (
  ibc_denom TEXT PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  last_attempt TIMESTAMP WITH TIME ZONE,
  attempts INT DEFAULT 0,
  error TEXT
);

CREATE INDEX IF NOT EXISTS idx_ibc_connections_chain ON api.ibc_connections(counterparty_chain_id);

CREATE INDEX IF NOT EXISTS idx_ibc_connections_state ON api.ibc_connections(state);

CREATE INDEX IF NOT EXISTS idx_ibc_denom_base ON api.ibc_denom_traces(base_denom);

CREATE INDEX IF NOT EXISTS idx_ibc_denom_channel ON api.ibc_denom_traces(source_channel);

CREATE INDEX IF NOT EXISTS idx_ibc_denom_pending_attempts
  ON api.ibc_denom_pending(attempts, last_attempt);

-- =============================================================================
-- NOTIFY FUNCTION
-- Sends notification when new IBC denom is queued for resolution
-- =============================================================================

CREATE OR REPLACE FUNCTION api.notify_ibc_denom_pending()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  PERFORM pg_notify('ibc_denom_pending', NEW.ibc_denom);
  RETURN NEW;
END;
$$;

-- =============================================================================
-- QUEUE UNKNOWN IBC DENOM FUNCTION
-- Called to queue an IBC denom for resolution if not already known
-- =============================================================================

CREATE OR REPLACE FUNCTION api.queue_unknown_ibc_denom(_ibc_denom TEXT)
RETURNS BOOLEAN
LANGUAGE plpgsql
AS $$
BEGIN
  -- Only queue if it looks like an IBC denom and isn't already resolved
  IF _ibc_denom IS NULL OR NOT _ibc_denom LIKE 'ibc/%' THEN
    RETURN FALSE;
  END IF;

  -- Check if already in denom_traces (resolved)
  IF EXISTS (SELECT 1 FROM api.ibc_denom_traces WHERE ibc_denom = _ibc_denom) THEN
    RETURN FALSE;
  END IF;

  -- Check if already in denom_metadata (resolved)
  IF EXISTS (SELECT 1 FROM api.denom_metadata WHERE denom = _ibc_denom AND ibc_source_denom IS NOT NULL) THEN
    RETURN FALSE;
  END IF;

  -- Insert into pending queue (ignore if already queued)
  INSERT INTO api.ibc_denom_pending (ibc_denom)
  VALUES (_ibc_denom)
  ON CONFLICT (ibc_denom) DO NOTHING;

  RETURN TRUE;
END;
$$;

-- =============================================================================
-- TRIGGER TO AUTO-QUEUE UNKNOWN IBC DENOMS FROM TRANSFERS
-- Extracts IBC denoms from MsgTransfer messages and queues for resolution
-- =============================================================================

CREATE OR REPLACE FUNCTION api.extract_and_queue_ibc_denoms()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  _denom TEXT;
  _token_denom TEXT;
BEGIN
  -- Only process IBC transfer messages
  IF NEW.type NOT IN (
    '/ibc.applications.transfer.v1.MsgTransfer',
    '/ibc.core.channel.v1.MsgRecvPacket'
  ) THEN
    RETURN NEW;
  END IF;

  -- Extract denom from metadata
  _token_denom := NEW.metadata->'token'->>'denom';

  -- For MsgRecvPacket, try to extract from packet data
  IF _token_denom IS NULL AND NEW.type = '/ibc.core.channel.v1.MsgRecvPacket' THEN
    -- Packet data might be in different locations
    _token_denom := NEW.metadata->'packet'->'data'->>'denom';
    IF _token_denom IS NULL THEN
      _token_denom := NEW.metadata->'packetData'->>'denom';
    END IF;
  END IF;

  -- Queue if it's an IBC denom
  IF _token_denom IS NOT NULL AND _token_denom LIKE 'ibc/%' THEN
    PERFORM api.queue_unknown_ibc_denom(_token_denom);
  END IF;

  RETURN NEW;
END;
$$;

-- =============================================================================
-- HELPER: Extract transfer details from message
-- Included here since migration 028 may have failed
-- =============================================================================

CREATE OR REPLACE FUNCTION api.extract_ibc_transfer_details(_message api.messages_main)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
  _result jsonb;
  _packet_data jsonb;
  _token_denom text;
  _token_amount text;
  _sender text;
  _receiver text;
  _source_channel text;
BEGIN
  IF _message.type = '/ibc.applications.transfer.v1.MsgTransfer' THEN
    _sender := _message.sender;
    _receiver := _message.metadata->>'receiver';
    _source_channel := COALESCE(
      _message.metadata->>'sourceChannel',
      _message.metadata->>'source_channel'
    );
    _token_denom := COALESCE(
      _message.metadata->'token'->>'denom',
      _message.metadata->>'denom'
    );
    _token_amount := COALESCE(
      _message.metadata->'token'->>'amount',
      _message.metadata->>'amount'
    );

  ELSIF _message.type = '/ibc.core.channel.v1.MsgRecvPacket' THEN
    _packet_data := COALESCE(
      _message.metadata->'packet'->'data',
      _message.metadata->'packetData',
      _message.metadata->'packet_data'
    );

    IF jsonb_typeof(_packet_data) = 'string' THEN
      BEGIN
        _packet_data := (_packet_data #>> '{}')::jsonb;
      EXCEPTION WHEN OTHERS THEN
        _packet_data := NULL;
      END;
    END IF;

    _sender := COALESCE(
      _packet_data->>'sender',
      _message.metadata->>'sender'
    );
    _receiver := COALESCE(
      _packet_data->>'receiver',
      _message.metadata->>'receiver'
    );
    _source_channel := COALESCE(
      _message.metadata->'packet'->>'sourceChannel',
      _message.metadata->'packet'->>'source_channel',
      _message.metadata->>'sourceChannel'
    );
    _token_denom := COALESCE(
      _packet_data->>'denom',
      _message.metadata->>'denom'
    );
    _token_amount := COALESCE(
      _packet_data->>'amount',
      _message.metadata->>'amount'
    );
  END IF;

  RETURN jsonb_build_object(
    'sender', _sender,
    'receiver', _receiver,
    'source_channel', _source_channel,
    'token_denom', _token_denom,
    'token_amount', _token_amount
  );
END;
$$;

-- =============================================================================
-- IBC RPC FUNCTIONS
-- =============================================================================

-- Get IBC connections with full route info
CREATE OR REPLACE FUNCTION api.get_ibc_connections(
  _limit INT DEFAULT 50,
  _offset INT DEFAULT 0,
  _chain_id TEXT DEFAULT NULL,
  _state TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE SQL STABLE
AS $$
  WITH filtered AS (
    SELECT *
    FROM api.ibc_connections
    WHERE (_chain_id IS NULL OR counterparty_chain_id = _chain_id)
      AND (_state IS NULL OR state = _state)
    ORDER BY counterparty_chain_id, channel_id
    LIMIT _limit OFFSET _offset
  ),
  total AS (
    SELECT COUNT(*) AS count
    FROM api.ibc_connections
    WHERE (_chain_id IS NULL OR counterparty_chain_id = _chain_id)
      AND (_state IS NULL OR state = _state)
  )
  SELECT jsonb_build_object(
    'data', COALESCE(jsonb_agg(
      jsonb_build_object(
        'channel_id', f.channel_id,
        'port_id', f.port_id,
        'connection_id', f.connection_id,
        'client_id', f.client_id,
        'counterparty_chain_id', f.counterparty_chain_id,
        'counterparty_channel_id', f.counterparty_channel_id,
        'counterparty_port_id', f.counterparty_port_id,
        'counterparty_client_id', f.counterparty_client_id,
        'counterparty_connection_id', f.counterparty_connection_id,
        'state', f.state,
        'ordering', f.ordering,
        'client_status', f.client_status,
        'is_active', f.state = 'STATE_OPEN' AND f.client_status = 'Active',
        'updated_at', f.updated_at
      )
      ORDER BY f.counterparty_chain_id, f.channel_id
    ), '[]'::jsonb),
    'pagination', jsonb_build_object(
      'total', (SELECT count FROM total),
      'limit', _limit,
      'offset', _offset,
      'has_next', _offset + _limit < (SELECT count FROM total),
      'has_prev', _offset > 0
    )
  )
  FROM filtered f;
$$;

-- Get IBC connection by channel
CREATE OR REPLACE FUNCTION api.get_ibc_connection(_channel_id TEXT, _port_id TEXT DEFAULT 'transfer')
RETURNS JSONB
LANGUAGE SQL STABLE
AS $$
  SELECT jsonb_build_object(
    'channel_id', channel_id,
    'port_id', port_id,
    'connection_id', connection_id,
    'client_id', client_id,
    'counterparty_chain_id', counterparty_chain_id,
    'counterparty_channel_id', counterparty_channel_id,
    'counterparty_port_id', counterparty_port_id,
    'counterparty_client_id', counterparty_client_id,
    'counterparty_connection_id', counterparty_connection_id,
    'state', state,
    'ordering', ordering,
    'client_status', client_status,
    'is_active', state = 'STATE_OPEN' AND client_status = 'Active',
    'updated_at', updated_at
  )
  FROM api.ibc_connections
  WHERE channel_id = _channel_id AND port_id = _port_id;
$$;

-- Get IBC denom traces
CREATE OR REPLACE FUNCTION api.get_ibc_denom_traces(
  _limit INT DEFAULT 50,
  _offset INT DEFAULT 0,
  _base_denom TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE SQL STABLE
AS $$
  WITH filtered AS (
    SELECT t.*, c.counterparty_chain_id
    FROM api.ibc_denom_traces t
    LEFT JOIN api.ibc_connections c ON t.source_channel = c.channel_id AND c.port_id = 'transfer'
    WHERE (_base_denom IS NULL OR t.base_denom ILIKE '%' || _base_denom || '%')
    ORDER BY t.base_denom, t.ibc_denom
    LIMIT _limit OFFSET _offset
  ),
  total AS (
    SELECT COUNT(*) AS count
    FROM api.ibc_denom_traces
    WHERE (_base_denom IS NULL OR base_denom ILIKE '%' || _base_denom || '%')
  )
  SELECT jsonb_build_object(
    'data', COALESCE(jsonb_agg(
      jsonb_build_object(
        'ibc_denom', f.ibc_denom,
        'base_denom', f.base_denom,
        'path', f.path,
        'source_channel', f.source_channel,
        'source_chain_id', COALESCE(f.source_chain_id, f.counterparty_chain_id),
        'symbol', f.symbol,
        'decimals', f.decimals,
        'updated_at', f.updated_at
      )
      ORDER BY f.base_denom, f.ibc_denom
    ), '[]'::jsonb),
    'pagination', jsonb_build_object(
      'total', (SELECT count FROM total),
      'limit', _limit,
      'offset', _offset,
      'has_next', _offset + _limit < (SELECT count FROM total),
      'has_prev', _offset > 0
    )
  )
  FROM filtered f;
$$;

-- Resolve IBC denom to base denom and source info
CREATE OR REPLACE FUNCTION api.resolve_ibc_denom(_ibc_denom TEXT)
RETURNS JSONB
LANGUAGE SQL STABLE
AS $$
  SELECT jsonb_build_object(
    'ibc_denom', t.ibc_denom,
    'base_denom', t.base_denom,
    'path', t.path,
    'source_channel', t.source_channel,
    'source_chain_id', COALESCE(t.source_chain_id, c.counterparty_chain_id),
    'symbol', t.symbol,
    'decimals', t.decimals,
    'route', jsonb_build_object(
      'channel_id', c.channel_id,
      'connection_id', c.connection_id,
      'client_id', c.client_id,
      'counterparty_channel_id', c.counterparty_channel_id,
      'counterparty_connection_id', c.counterparty_connection_id,
      'counterparty_client_id', c.counterparty_client_id
    )
  )
  FROM api.ibc_denom_traces t
  LEFT JOIN api.ibc_connections c ON t.source_channel = c.channel_id AND c.port_id = 'transfer'
  WHERE t.ibc_denom = _ibc_denom;
$$;

-- Get unique counterparty chains
CREATE OR REPLACE FUNCTION api.get_ibc_chains()
RETURNS JSONB
LANGUAGE SQL STABLE
AS $$
  SELECT COALESCE(jsonb_agg(
    jsonb_build_object(
      'chain_id', counterparty_chain_id,
      'channel_count', channel_count,
      'open_channels', open_channels,
      'active_channels', active_channels
    )
    ORDER BY counterparty_chain_id
  ), '[]'::jsonb)
  FROM (
    SELECT
      counterparty_chain_id,
      COUNT(*) AS channel_count,
      COUNT(*) FILTER (WHERE state = 'STATE_OPEN') AS open_channels,
      COUNT(*) FILTER (WHERE state = 'STATE_OPEN' AND client_status = 'Active') AS active_channels
    FROM api.ibc_connections
    WHERE counterparty_chain_id IS NOT NULL
    GROUP BY counterparty_chain_id
  ) chains;
$$;

-- Get chain parameters as JSON object
CREATE OR REPLACE FUNCTION api.get_chain_params()
RETURNS JSONB
LANGUAGE SQL STABLE
AS $$
  SELECT COALESCE(jsonb_object_agg(key, value), '{}'::jsonb)
  FROM api.chain_params;
$$;

-- Function to get all messages for an address (used by yaci metrics collectors)
-- Returns messages where the address is sender or in the mentions array
-- Includes the transaction error field for filtering successful transactions
CREATE OR REPLACE FUNCTION api.get_messages_for_address(_address text)
RETURNS SETOF api.message_with_error
LANGUAGE sql STABLE
AS $$
  SELECT
    m.id,
    m.message_index,
    m.type,
    m.sender,
    m.mentions,
    m.metadata,
    t.error
  FROM api.messages_main m
  JOIN api.transactions_main t ON m.id = t.id
  WHERE m.sender = _address
     OR _address = ANY(m.mentions)
     OR m.metadata->>'toAddress' = _address
  ORDER BY t.height DESC, m.message_index;
$$;

-- =============================================================================
-- HELPER: RESOLVE DENOM (returns symbol/decimals for any denom)
-- Works for native, IBC, and EVM denoms
-- =============================================================================

CREATE OR REPLACE FUNCTION api.resolve_denom(_denom TEXT)
RETURNS JSONB
LANGUAGE sql
STABLE
AS $$
  SELECT COALESCE(
    -- First try denom_metadata (most comprehensive)
    (SELECT jsonb_build_object(
      'denom', denom,
      'symbol', symbol,
      'decimals', decimals,
      'is_native', is_native,
      'source_chain', ibc_source_chain,
      'source_denom', ibc_source_denom
    ) FROM api.denom_metadata WHERE denom = _denom),
    -- Then try ibc_denom_traces
    (SELECT jsonb_build_object(
      'denom', ibc_denom,
      'symbol', COALESCE(symbol, base_denom),
      'decimals', COALESCE(decimals, 6),
      'is_native', false,
      'source_chain', source_chain_id,
      'source_denom', base_denom
    ) FROM api.ibc_denom_traces WHERE ibc_denom = _denom),
    -- Fallback: parse common patterns
    CASE
      WHEN _denom LIKE 'u%' THEN jsonb_build_object(
        'denom', _denom,
        'symbol', UPPER(SUBSTRING(_denom FROM 2)),
        'decimals', 6,
        'is_native', true,
        'source_chain', NULL,
        'source_denom', NULL
      )
      WHEN _denom LIKE 'a%' THEN jsonb_build_object(
        'denom', _denom,
        'symbol', UPPER(SUBSTRING(_denom FROM 2)),
        'decimals', 18,
        'is_native', true,
        'source_chain', NULL,
        'source_denom', NULL
      )
      WHEN _denom LIKE 'ibc/%' THEN jsonb_build_object(
        'denom', _denom,
        'symbol', 'IBC/' || SUBSTRING(_denom FROM 5 FOR 8) || '...',
        'decimals', 6,
        'is_native', false,
        'source_chain', NULL,
        'source_denom', NULL
      )
      ELSE jsonb_build_object(
        'denom', _denom,
        'symbol', UPPER(_denom),
        'decimals', 6,
        'is_native', NULL,
        'source_chain', NULL,
        'source_denom', NULL
      )
    END
  );
$$;

-- =============================================================================
-- IBC TRANSFER STATISTICS (unchanged but re-created for consistency)
-- =============================================================================

CREATE OR REPLACE FUNCTION api.get_ibc_stats()
RETURNS jsonb
LANGUAGE sql
STABLE
AS $$
  WITH transfer_stats AS (
    SELECT
      COUNT(*) FILTER (WHERE type = '/ibc.applications.transfer.v1.MsgTransfer') as outgoing_transfers,
      COUNT(*) FILTER (WHERE type = '/ibc.core.channel.v1.MsgRecvPacket') as incoming_transfers,
      COUNT(*) FILTER (WHERE type = '/ibc.core.channel.v1.MsgAcknowledgement') as completed_transfers,
      COUNT(*) FILTER (WHERE type = '/ibc.core.channel.v1.MsgTimeout') as timed_out_transfers,
      COUNT(*) FILTER (WHERE type = '/ibc.core.client.v1.MsgUpdateClient') as relayer_updates
    FROM api.messages_main
    WHERE type LIKE '/ibc%'
  ),
  channel_stats AS (
    SELECT
      COUNT(*) as total_channels,
      COUNT(*) FILTER (WHERE state = 'STATE_OPEN') as open_channels,
      COUNT(*) FILTER (WHERE state = 'STATE_OPEN' AND client_status = 'Active') as active_channels,
      COUNT(DISTINCT counterparty_chain_id) as connected_chains
    FROM api.ibc_connections
  ),
  denom_stats AS (
    SELECT COUNT(*) as total_denoms
    FROM api.ibc_denom_traces
  )
  SELECT jsonb_build_object(
    'outgoing_transfers', ts.outgoing_transfers,
    'incoming_transfers', ts.incoming_transfers,
    'completed_transfers', ts.completed_transfers,
    'timed_out_transfers', ts.timed_out_transfers,
    'relayer_updates', ts.relayer_updates,
    'total_channels', cs.total_channels,
    'open_channels', cs.open_channels,
    'active_channels', cs.active_channels,
    'connected_chains', cs.connected_chains,
    'total_denoms', ds.total_denoms
  )
  FROM transfer_stats ts, channel_stats cs, denom_stats ds;
$$;

-- =============================================================================
-- GET IBC TRANSFERS (paginated with direction filter)
-- =============================================================================

CREATE OR REPLACE FUNCTION api.get_ibc_transfers(
  _limit integer DEFAULT 20,
  _offset integer DEFAULT 0,
  _direction text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE sql
STABLE
AS $$
  WITH filtered_messages AS (
    SELECT
      m.*,
      t.height,
      t.timestamp,
      t.error,
      CASE
        WHEN m.type = '/ibc.applications.transfer.v1.MsgTransfer' THEN 'outgoing'
        WHEN m.type = '/ibc.core.channel.v1.MsgRecvPacket' THEN 'incoming'
        ELSE 'other'
      END as direction
    FROM api.messages_main m
    JOIN api.transactions_main t ON m.id = t.id
    WHERE m.type IN (
      '/ibc.applications.transfer.v1.MsgTransfer',
      '/ibc.core.channel.v1.MsgRecvPacket'
    )
    AND (_direction IS NULL OR
      (_direction = 'outgoing' AND m.type = '/ibc.applications.transfer.v1.MsgTransfer') OR
      (_direction = 'incoming' AND m.type = '/ibc.core.channel.v1.MsgRecvPacket')
    )
  ),
  total AS (
    SELECT COUNT(*)::int as count FROM filtered_messages
  ),
  paginated AS (
    SELECT * FROM filtered_messages
    ORDER BY height DESC, message_index
    LIMIT _limit OFFSET _offset
  ),
  transfers AS (
    SELECT
      p.id as tx_hash,
      p.height,
      p.timestamp,
      p.direction,
      p.error,
      api.extract_ibc_transfer_details(ROW(p.id, p.message_index, p.type, p.sender, p.mentions, p.metadata)::api.messages_main) as details
    FROM paginated p
  )
  SELECT jsonb_build_object(
    'data', COALESCE((
      SELECT jsonb_agg(jsonb_build_object(
        'tx_hash', tr.tx_hash,
        'height', tr.height,
        'timestamp', tr.timestamp,
        'direction', tr.direction,
        'sender', tr.details->>'sender',
        'receiver', tr.details->>'receiver',
        'source_channel', tr.details->>'source_channel',
        'token_denom', tr.details->>'token_denom',
        'token_amount', tr.details->>'token_amount',
        'resolved_denom', api.resolve_denom(tr.details->>'token_denom'),
        'counterparty_chain', (
          SELECT c.counterparty_chain_id
          FROM api.ibc_connections c
          WHERE c.channel_id = tr.details->>'source_channel' AND c.port_id = 'transfer'
        ),
        'success', tr.error IS NULL OR tr.error = ''
      ) ORDER BY tr.height DESC)
      FROM transfers tr
    ), '[]'::jsonb),
    'pagination', jsonb_build_object(
      'total', (SELECT count FROM total),
      'limit', _limit,
      'offset', _offset,
      'has_next', _offset + _limit < (SELECT count FROM total),
      'has_prev', _offset > 0
    )
  );
$$;

-- =============================================================================
-- GET IBC TRANSFERS BY ADDRESS
-- =============================================================================

CREATE OR REPLACE FUNCTION api.get_ibc_transfers_by_address(
  _address text,
  _limit integer DEFAULT 10,
  _offset integer DEFAULT 0
)
RETURNS jsonb
LANGUAGE sql
STABLE
AS $$
  WITH filtered_messages AS (
    SELECT
      m.*,
      t.height,
      t.timestamp,
      t.error,
      CASE
        WHEN m.type = '/ibc.applications.transfer.v1.MsgTransfer' THEN 'outgoing'
        WHEN m.type = '/ibc.core.channel.v1.MsgRecvPacket' THEN 'incoming'
        ELSE 'other'
      END as direction
    FROM api.messages_main m
    JOIN api.transactions_main t ON m.id = t.id
    WHERE m.type IN (
      '/ibc.applications.transfer.v1.MsgTransfer',
      '/ibc.core.channel.v1.MsgRecvPacket'
    )
    AND (
      m.sender = _address
      OR m.metadata->>'receiver' = _address
      OR _address = ANY(m.mentions)
      -- Also check packet data for incoming transfers
      OR m.metadata->'packet'->'data'->>'receiver' = _address
      OR m.metadata->'packetData'->>'receiver' = _address
    )
  ),
  total AS (
    SELECT COUNT(*)::int as count FROM filtered_messages
  ),
  paginated AS (
    SELECT * FROM filtered_messages
    ORDER BY height DESC, message_index
    LIMIT _limit OFFSET _offset
  ),
  transfers AS (
    SELECT
      p.id as tx_hash,
      p.height,
      p.timestamp,
      p.direction,
      p.error,
      api.extract_ibc_transfer_details(ROW(p.id, p.message_index, p.type, p.sender, p.mentions, p.metadata)::api.messages_main) as details
    FROM paginated p
  )
  SELECT jsonb_build_object(
    'data', COALESCE((
      SELECT jsonb_agg(jsonb_build_object(
        'tx_hash', tr.tx_hash,
        'height', tr.height,
        'timestamp', tr.timestamp,
        'direction', tr.direction,
        'sender', tr.details->>'sender',
        'receiver', tr.details->>'receiver',
        'source_channel', tr.details->>'source_channel',
        'token_denom', tr.details->>'token_denom',
        'token_amount', tr.details->>'token_amount',
        'resolved_denom', api.resolve_denom(tr.details->>'token_denom'),
        'counterparty_chain', (
          SELECT c.counterparty_chain_id
          FROM api.ibc_connections c
          WHERE c.channel_id = tr.details->>'source_channel' AND c.port_id = 'transfer'
        ),
        'success', tr.error IS NULL OR tr.error = ''
      ) ORDER BY tr.height DESC)
      FROM transfers tr
    ), '[]'::jsonb),
    'pagination', jsonb_build_object(
      'total', (SELECT count FROM total),
      'limit', _limit,
      'offset', _offset,
      'has_next', _offset + _limit < (SELECT count FROM total),
      'has_prev', _offset > 0
    )
  );
$$;

-- =============================================================================
-- GET IBC CHANNEL ACTIVITY
-- =============================================================================

CREATE OR REPLACE FUNCTION api.get_ibc_channel_activity()
RETURNS jsonb
LANGUAGE sql
STABLE
AS $$
  WITH channel_activity AS (
    SELECT
      COALESCE(
        m.metadata->>'sourceChannel',
        m.metadata->>'source_channel'
      ) as channel_id,
      COUNT(*) as transfer_count,
      COUNT(*) FILTER (WHERE t.error IS NULL OR t.error = '') as successful_transfers
    FROM api.messages_main m
    JOIN api.transactions_main t ON m.id = t.id
    WHERE m.type = '/ibc.applications.transfer.v1.MsgTransfer'
    AND (m.metadata->>'sourceChannel' IS NOT NULL OR m.metadata->>'source_channel' IS NOT NULL)
    GROUP BY COALESCE(m.metadata->>'sourceChannel', m.metadata->>'source_channel')
  )
  SELECT COALESCE(jsonb_agg(jsonb_build_object(
    'channel_id', ca.channel_id,
    'transfer_count', ca.transfer_count,
    'successful_transfers', ca.successful_transfers,
    'counterparty_chain_id', c.counterparty_chain_id,
    'state', c.state,
    'client_status', c.client_status
  ) ORDER BY ca.transfer_count DESC), '[]'::jsonb)
  FROM channel_activity ca
  LEFT JOIN api.ibc_connections c ON ca.channel_id = c.channel_id AND c.port_id = 'transfer';
$$;

-- =============================================================================
-- FIX: get_ibc_volume_timeseries response structure
-- Frontend expects { timeseries, summary } not { hours, data, channels }
-- =============================================================================

CREATE OR REPLACE FUNCTION api.get_ibc_volume_timeseries(
  _hours integer DEFAULT 24,
  _channel text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE sql
STABLE
AS $$
  WITH ibc_messages AS (
    SELECT
      m.*,
      t.timestamp,
      t.error,
      api.extract_ibc_transfer_details(m) as details,
      CASE
        WHEN m.type = '/ibc.applications.transfer.v1.MsgTransfer' THEN 'outgoing'
        WHEN m.type = '/ibc.core.channel.v1.MsgRecvPacket' THEN 'incoming'
        ELSE 'other'
      END as direction
    FROM api.messages_main m
    JOIN api.transactions_main t ON m.id = t.id
    WHERE m.type IN (
      '/ibc.applications.transfer.v1.MsgTransfer',
      '/ibc.core.channel.v1.MsgRecvPacket'
    )
    AND t.timestamp >= NOW() - (_hours || ' hours')::interval
    AND (t.error IS NULL OR t.error = '')
  ),
  filtered AS (
    SELECT
      timestamp,
      direction,
      details->>'source_channel' AS channel
    FROM ibc_messages
    WHERE _channel IS NULL OR details->>'source_channel' = _channel
  ),
  hourly_volume AS (
    SELECT
      date_trunc('hour', timestamp) AS hour_bucket,
      direction,
      COUNT(*) AS transfer_count
    FROM filtered
    WHERE timestamp IS NOT NULL
    GROUP BY date_trunc('hour', timestamp), direction
  ),
  time_series AS (
    SELECT generate_series(
      date_trunc('hour', NOW() - (_hours || ' hours')::interval),
      date_trunc('hour', NOW()),
      '1 hour'::interval
    ) AS hour_bucket
  ),
  timeseries_data AS (
    SELECT
      ts.hour_bucket AS hour,
      COALESCE(SUM(hv.transfer_count) FILTER (WHERE hv.direction = 'outgoing'), 0)::int AS outgoing_count,
      COALESCE(SUM(hv.transfer_count) FILTER (WHERE hv.direction = 'incoming'), 0)::int AS incoming_count,
      COALESCE(SUM(hv.transfer_count), 0)::int AS total_count
    FROM time_series ts
    LEFT JOIN hourly_volume hv ON hv.hour_bucket = ts.hour_bucket
    GROUP BY ts.hour_bucket
    ORDER BY ts.hour_bucket DESC
  ),
  summary_data AS (
    SELECT
      COALESCE(SUM(transfer_count) FILTER (WHERE direction = 'outgoing'), 0)::int AS total_outgoing,
      COALESCE(SUM(transfer_count) FILTER (WHERE direction = 'incoming'), 0)::int AS total_incoming,
      COALESCE(SUM(transfer_count), 0)::int AS total_transfers
    FROM hourly_volume
  ),
  peak_data AS (
    SELECT
      hour_bucket AS peak_hour,
      SUM(transfer_count)::int AS peak_count
    FROM hourly_volume
    GROUP BY hour_bucket
    ORDER BY SUM(transfer_count) DESC
    LIMIT 1
  )
  SELECT jsonb_build_object(
    'timeseries', COALESCE((
      SELECT jsonb_agg(jsonb_build_object(
        'hour', td.hour,
        'outgoing_count', td.outgoing_count,
        'incoming_count', td.incoming_count,
        'total_count', td.total_count
      ) ORDER BY td.hour DESC)
      FROM timeseries_data td
    ), '[]'::jsonb),
    'summary', jsonb_build_object(
      'total_outgoing', (SELECT total_outgoing FROM summary_data),
      'total_incoming', (SELECT total_incoming FROM summary_data),
      'total_transfers', (SELECT total_transfers FROM summary_data),
      'peak_hour', (SELECT peak_hour FROM peak_data),
      'peak_count', COALESCE((SELECT peak_count FROM peak_data), 0)
    )
  );
$$;

-- =============================================================================
-- NEW: IBC Heat Map Analytics Function
-- Provides comprehensive data for heat map visualizations
-- =============================================================================

CREATE OR REPLACE FUNCTION api.get_ibc_heatmap_data(
  _timeframe text DEFAULT '7d',
  _metric text DEFAULT 'count',
  _direction text DEFAULT NULL,
  _channel text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE sql
STABLE
AS $$
  WITH params AS (
    SELECT
      CASE _timeframe
        WHEN '24h' THEN interval '24 hours'
        WHEN '48h' THEN interval '48 hours'
        WHEN '7d' THEN interval '7 days'
        WHEN '30d' THEN interval '30 days'
        ELSE interval '7 days'
      END AS lookback,
      CASE _timeframe
        WHEN '24h' THEN 'hour'
        WHEN '48h' THEN 'hour'
        WHEN '7d' THEN 'hour'
        WHEN '30d' THEN 'day'
        ELSE 'hour'
      END AS granularity
  ),
  ibc_data AS (
    SELECT
      m.*,
      t.timestamp,
      t.error,
      api.extract_ibc_transfer_details(m) as details,
      CASE
        WHEN m.type = '/ibc.applications.transfer.v1.MsgTransfer' THEN 'outgoing'
        WHEN m.type = '/ibc.core.channel.v1.MsgRecvPacket' THEN 'incoming'
      END as direction
    FROM api.messages_main m
    JOIN api.transactions_main t ON m.id = t.id
    CROSS JOIN params p
    WHERE m.type IN (
      '/ibc.applications.transfer.v1.MsgTransfer',
      '/ibc.core.channel.v1.MsgRecvPacket'
    )
    AND t.timestamp >= NOW() - p.lookback
    AND (t.error IS NULL OR t.error = '')
    AND (_direction IS NULL OR
      (_direction = 'outgoing' AND m.type = '/ibc.applications.transfer.v1.MsgTransfer') OR
      (_direction = 'incoming' AND m.type = '/ibc.core.channel.v1.MsgRecvPacket')
    )
  ),
  filtered AS (
    SELECT
      timestamp,
      direction,
      details->>'source_channel' AS channel,
      COALESCE((details->>'token_amount')::numeric, 0) AS amount
    FROM ibc_data
    WHERE _channel IS NULL OR details->>'source_channel' = _channel
  ),
  hourly_data AS (
    SELECT
      date_trunc('hour', timestamp) AS bucket,
      EXTRACT(DOW FROM timestamp)::int AS day_of_week,
      EXTRACT(HOUR FROM timestamp)::int AS hour_of_day,
      direction,
      COUNT(*) AS transfer_count,
      SUM(amount) AS total_volume
    FROM filtered
    WHERE (SELECT granularity FROM params) = 'hour'
    GROUP BY 1, 2, 3, 4
  ),
  daily_data AS (
    SELECT
      date_trunc('day', timestamp) AS bucket,
      EXTRACT(DOW FROM timestamp)::int AS day_of_week,
      NULL::int AS hour_of_day,
      direction,
      COUNT(*) AS transfer_count,
      SUM(amount) AS total_volume
    FROM filtered
    WHERE (SELECT granularity FROM params) = 'day'
    GROUP BY 1, 2, 4
  ),
  combined AS (
    SELECT * FROM hourly_data
    UNION ALL
    SELECT * FROM daily_data
  ),
  timeseries AS (
    SELECT
      bucket,
      COALESCE(SUM(transfer_count) FILTER (WHERE direction = 'outgoing'), 0) AS outgoing_count,
      COALESCE(SUM(transfer_count) FILTER (WHERE direction = 'incoming'), 0) AS incoming_count,
      COALESCE(SUM(total_volume) FILTER (WHERE direction = 'outgoing'), 0) AS outgoing_volume,
      COALESCE(SUM(total_volume) FILTER (WHERE direction = 'incoming'), 0) AS incoming_volume
    FROM combined
    GROUP BY bucket
    ORDER BY bucket
  ),
  heatmap_matrix AS (
    SELECT
      day_of_week,
      hour_of_day,
      COALESCE(SUM(transfer_count), 0) AS count,
      COALESCE(SUM(total_volume), 0) AS volume
    FROM combined
    WHERE hour_of_day IS NOT NULL
    GROUP BY day_of_week, hour_of_day
  ),
  summary AS (
    SELECT
      COALESCE(SUM(transfer_count) FILTER (WHERE direction = 'outgoing'), 0) AS total_outgoing_count,
      COALESCE(SUM(transfer_count) FILTER (WHERE direction = 'incoming'), 0) AS total_incoming_count,
      COALESCE(SUM(total_volume) FILTER (WHERE direction = 'outgoing'), 0) AS total_outgoing_volume,
      COALESCE(SUM(total_volume) FILTER (WHERE direction = 'incoming'), 0) AS total_incoming_volume,
      COALESCE(MAX(transfer_count), 0) AS peak_count,
      COALESCE(MAX(total_volume), 0) AS peak_volume
    FROM combined
  ),
  channel_breakdown AS (
    SELECT
      details->>'source_channel' AS channel,
      COUNT(*) AS transfer_count,
      SUM(COALESCE((details->>'token_amount')::numeric, 0)) AS total_volume
    FROM ibc_data
    WHERE details->>'source_channel' IS NOT NULL
    GROUP BY 1
    ORDER BY transfer_count DESC
    LIMIT 10
  )
  SELECT jsonb_build_object(
    'timeframe', _timeframe,
    'metric', _metric,
    'direction_filter', _direction,
    'channel_filter', _channel,
    'granularity', (SELECT granularity FROM params),
    'timeseries', COALESCE((
      SELECT jsonb_agg(jsonb_build_object(
        'timestamp', bucket,
        'outgoing_count', outgoing_count,
        'incoming_count', incoming_count,
        'outgoing_volume', outgoing_volume,
        'incoming_volume', incoming_volume,
        'total_count', outgoing_count + incoming_count,
        'total_volume', outgoing_volume + incoming_volume
      ) ORDER BY bucket)
      FROM timeseries
    ), '[]'::jsonb),
    'heatmap', COALESCE((
      SELECT jsonb_agg(jsonb_build_object(
        'day', day_of_week,
        'hour', hour_of_day,
        'count', count,
        'volume', volume
      ))
      FROM heatmap_matrix
    ), '[]'::jsonb),
    'summary', (
      SELECT jsonb_build_object(
        'total_outgoing_count', total_outgoing_count,
        'total_incoming_count', total_incoming_count,
        'total_outgoing_volume', total_outgoing_volume,
        'total_incoming_volume', total_incoming_volume,
        'total_transfers', total_outgoing_count + total_incoming_count,
        'total_volume', total_outgoing_volume + total_incoming_volume,
        'peak_hourly_count', peak_count,
        'peak_hourly_volume', peak_volume
      )
      FROM summary
    ),
    'top_channels', COALESCE((
      SELECT jsonb_agg(jsonb_build_object(
        'channel', channel,
        'count', transfer_count,
        'volume', total_volume
      ))
      FROM channel_breakdown
    ), '[]'::jsonb)
  );
$$;

CREATE TRIGGER trg_ibc_denom_pending_notify
  AFTER INSERT ON api.ibc_denom_pending
  FOR EACH ROW
  EXECUTE FUNCTION api.notify_ibc_denom_pending();

CREATE TRIGGER trg_queue_ibc_denoms
  AFTER INSERT ON api.messages_main
  FOR EACH ROW
  EXECUTE FUNCTION api.extract_and_queue_ibc_denoms();

-- IBC and chain params functions
GRANT EXECUTE ON FUNCTION api.get_chain_params() TO web_anon;

GRANT EXECUTE ON FUNCTION api.get_ibc_connections(int, int, text, text) TO web_anon;

GRANT EXECUTE ON FUNCTION api.get_ibc_connection(text, text) TO web_anon;

GRANT EXECUTE ON FUNCTION api.get_ibc_denom_traces(int, int, text) TO web_anon;

GRANT EXECUTE ON FUNCTION api.resolve_ibc_denom(text) TO web_anon;

GRANT EXECUTE ON FUNCTION api.get_ibc_chains() TO web_anon;

-- =============================================================================
-- GRANT PERMISSIONS
-- =============================================================================

GRANT SELECT ON api.ibc_connections TO web_anon;

GRANT SELECT ON api.ibc_denom_traces TO web_anon;

GRANT SELECT ON api.chain_params TO web_anon;

GRANT EXECUTE ON FUNCTION api.get_chain_params() TO web_anon;

-- Grant execute permission to web_anon role
GRANT EXECUTE ON FUNCTION api.get_messages_for_address(text) TO web_anon;

-- =============================================================================
-- GRANT PERMISSIONS
-- =============================================================================

GRANT EXECUTE ON FUNCTION api.get_ibc_stats() TO web_anon;

GRANT EXECUTE ON FUNCTION api.get_ibc_transfers(int, int, text) TO web_anon;

GRANT EXECUTE ON FUNCTION api.get_ibc_transfers_by_address(text, int, int) TO web_anon;

GRANT EXECUTE ON FUNCTION api.get_ibc_channel_activity() TO web_anon;

GRANT EXECUTE ON FUNCTION api.get_ibc_volume_timeseries(int, text) TO web_anon;

-- =============================================================================
-- GRANT PERMISSIONS
-- =============================================================================

GRANT SELECT ON api.ibc_denom_pending TO web_anon;

GRANT EXECUTE ON FUNCTION api.queue_unknown_ibc_denom(text) TO web_anon;

GRANT EXECUTE ON FUNCTION api.resolve_denom(text) TO web_anon;

-- =============================================================================
-- GRANT PERMISSIONS
-- =============================================================================

GRANT EXECUTE ON FUNCTION api.extract_ibc_transfer_details(api.messages_main) TO web_anon;

GRANT EXECUTE ON FUNCTION api.get_ibc_stats() TO web_anon;

GRANT EXECUTE ON FUNCTION api.get_ibc_volume_timeseries(integer, text) TO web_anon;

GRANT EXECUTE ON FUNCTION api.get_ibc_heatmap_data(text, text, text, text) TO web_anon;

CREATE INDEX IF NOT EXISTS idx_tx_error_not_null ON api.transactions_main(id) WHERE error IS NOT NULL;

-- =============================================================================
-- CHAIN FEATURES (capability advertisement for the frontend)
-- =============================================================================

CREATE TABLE IF NOT EXISTS api.chain_features (
  chain_id TEXT PRIMARY KEY,
  features TEXT[] NOT NULL DEFAULT '{}'
);

GRANT SELECT ON api.chain_features TO web_anon;

-- Daily active addresses (unique senders per day). transactions_main supplies the
-- timestamp; messages_main has no timestamp column.
CREATE OR REPLACE VIEW api.daily_active_addresses AS
SELECT
  DATE(t.timestamp) AS date,
  COUNT(DISTINCT m.sender) AS active_addresses
FROM api.messages_main m
JOIN api.transactions_main t ON t.id = m.id
WHERE t.timestamp IS NOT NULL AND m.sender IS NOT NULL
GROUP BY DATE(t.timestamp)
ORDER BY date DESC;

GRANT SELECT ON api.daily_active_addresses TO web_anon;

COMMIT;
